### PR TITLE
Update for psc 0.10

### PR DESCRIPTION
**Pull request by hdgarrood**
Also contains a fix for #2.

### CODE REVIEW

**Comment by hdgarrood** [comment]
I should check actually: are you still interested in maintaining / able to maintain this library?

**Comment by hdgarrood** [comment]
Oops, missed the tests!

**Comment by matthieubulte** [comment]
Hi Garry, thanks for the PR!

Small comment in the code. Otherwise it's good to merge.

I'm currently a bit busy with work&study so if you feel like taking the ownership here, I'd be more than happy!

**Comment by hdgarrood** [comment]
You're welcome :) I'm not sure what's happened but I can't see your comment.

**Comment by matthieubulte** [comment]
The comment was about replacing epsilon equality by structural equality.

I agree that breaking equality laws is pretty sad but equality won't be usable in practice if structural.

Maybe we should think about introducing an `approxEq` function, or introduce a `ApproxEq` typeclass for this. I don't know what's best.

**Comment by hdgarrood** [comment]
I don't think the `Eq` instance I am proposing will be unusable in practice, given that this is pretty much the same equality as what floating point uses, and floating point seems to have held the title of being the dominant representation for real numbers for quite some time now. It's also the instance that Haskell uses: http://hackage.haskell.org/package/base-4.9.1.0/docs/src/Data.Complex.html#line-50

If we were going to go down the typeclass route for approximate equality, I think the right abstraction would probably be a [metric space](https://en.wikipedia.org/wiki/Metric_space).

**Comment by matthieubulte** [comment]
Right, let's then merge this!

**Comment by hdgarrood** [comment]
Oops, sorry, I think the tests are still broken! I'll send another PR in a bit.

**Pull request merged**
